version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"