# Generated by Django 4.0.5 on 2022-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_newpost_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
