# Generated by Django 4.0.5 on 2022-06-13 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_newpost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
