# Generated by Django 4.0.5 on 2022-06-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_newpost_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Post',
        ),
    ]
