# Generated by Django 4.0.5 on 2022-06-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_newpost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
    ]
