name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.4"
    - name: Install Dependencies
      run: |
        pip3 install --user django
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py makemigrations network
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test